steps:
  # - id: build-arm32
  #   name: 'gcr.io/cloud-builders/docker'
  #   args: ['build', '-t=gcr.io/$PROJECT_ID/cloudbuild-arm32:arm32', '-f=Dockerfile', '.']
  #   waitFor: ['-']

  # - id: build-cloudrun
  #   name: 'gcr.io/cloud-builders/docker'
  #   args: ['build', '-t=gcr.io/$PROJECT_ID/cloudbuild-arm32:cloudrun', '-f=Dockerfile.cloudrun', '.']
  #   waitFor: ['-']

  # - id: build-golang
  #   name: 'gcr.io/cloud-builders/docker'
  #   args: ['build', '-t=gcr.io/$PROJECT_ID/cloudbuild-arm32:golang', '-f=Dockerfile.golang', '.']
  #   waitFor: ['-']

  # - id: prep-shim
  #   name: 'gcr.io/cloud-builders/docker'
  #   args: ['run', '--rm', '--privileged', 'multiarch/qemu-user-static:register', '--reset']
  #   waitFor: ['-']

  - id: prep-shim
    name: multiarch/qemu-user-static:register
    args: ['--reset']
    waitFor: ['-']    

  - id: cache-led
    name: 'gcr.io/cloud-builders/docker'
    args: ['pull', 'gcr.io/$PROJECT_ID/cloudbuild-arm32:led']
    waitFor: ['-']    

  - id: cache-buttons
    name: 'gcr.io/cloud-builders/docker'
    args: ['pull', 'gcr.io/$PROJECT_ID/cloudbuild-arm32:buttons']
    waitFor: ['-']    

  - id: cache-tof
    name: 'gcr.io/cloud-builders/docker'
    args: ['pull', 'gcr.io/$PROJECT_ID/cloudbuild-arm32:tof']
    waitFor: ['-']    

  - id: build-led
    name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-t=gcr.io/$PROJECT_ID/cloudbuild-arm32:led'
      - '-f=Dockerfile.led' 
      - '--cache-from=gcr.io/$PROJECT_ID/cloudbuild-arm32:led' 
      - '.'
    waitFor: [prep-shim, cache-led]

  # - id: build-inky
  #   name: 'gcr.io/cloud-builders/docker'
  #   args: ['build', '-t=gcr.io/$PROJECT_ID/cloudbuild-arm32:inky', '-f=Dockerfile.inky', '.']
  #   waitFor: [prep-shim]    

  - id: build-tof
    name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-t=gcr.io/$PROJECT_ID/cloudbuild-arm32:tof'
      - '-f=Dockerfile.tof'
      - '--cache-from=gcr.io/$PROJECT_ID/cloudbuild-arm32:tof' 
      - '.'
    waitFor: [prep-shim, cache-tof]   

  - id: build-buttons
    name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-t=gcr.io/$PROJECT_ID/cloudbuild-arm32:buttons'
      - '-f=Dockerfile.buttons' 
      - '--cache-from=gcr.io/$PROJECT_ID/cloudbuild-arm32:buttons' 
      - '.'
    waitFor: [prep-shim, cache-buttons]       

  # - id: push-cloudrun
  #   name: 'gcr.io/cloud-builders/docker'
  #   args: ["push", "gcr.io/$PROJECT_ID/cloudbuild-arm32:cloudrun"]
  #   waitFor: [build-cloudrun]

  - id: push-led
    name: 'gcr.io/cloud-builders/docker'
    args: ["push", "gcr.io/$PROJECT_ID/cloudbuild-arm32:led"]
    waitFor: [build-led]

  # - id: push-inky
  #   name: 'gcr.io/cloud-builders/docker'
  #   args: ["push", "gcr.io/$PROJECT_ID/cloudbuild-arm32:inky"]
  #   waitFor: [build-inky]

  - id: push-tof
    name: 'gcr.io/cloud-builders/docker'
    args: ["push", "gcr.io/$PROJECT_ID/cloudbuild-arm32:tof"]
    waitFor: [build-tof]

  - id: push-buttons
    name: 'gcr.io/cloud-builders/docker'
    args: ["push", "gcr.io/$PROJECT_ID/cloudbuild-arm32:buttons"]
    waitFor: [build-buttons]

  # - id: deploy-cloudrun
  #   name: 'gcr.io/cloud-builders/gcloud'
  #   args: ['alpha', 'serverless', 'deploy', 'cloudbuild-arm32', '--image', 'gcr.io/$PROJECT_ID/cloudbuild-arm32:cloudrun', '--region', 'us-central1']
  #   waitFor: [push-cloudrun]

images:
  # - 'gcr.io/$PROJECT_ID/cloudbuild-arm32:arm32'
  # - 'gcr.io/$PROJECT_ID/cloudbuild-arm32:cloudrun'
  # - 'gcr.io/$PROJECT_ID/cloudbuild-arm32:golang'
  - 'gcr.io/$PROJECT_ID/cloudbuild-arm32:led'
  # - 'gcr.io/$PROJECT_ID/cloudbuild-arm32:inky'
  - 'gcr.io/$PROJECT_ID/cloudbuild-arm32:buttons'
  - 'gcr.io/$PROJECT_ID/cloudbuild-arm32:tof'

tags:
  - cloud-run-playground
  - arm32

timeout: 1200s

options:
 machineType: UNSPECIFIED