steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t=gcr.io/$PROJECT_ID/cloudbuild-arm32:arm32', '-f=Dockerfile', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t=gcr.io/$PROJECT_ID/cloudbuild-arm32:cloudrun', '-f=Dockerfile.cloudrun', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t=gcr.io/$PROJECT_ID/cloudbuild-arm32:golang', '-f=Dockerfile.golang', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ["push", "gcr.io/$PROJECT_ID/cloudbuild-arm32:cloudrun"]
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['alpha', 'serverless', 'deploy', 'cloudbuild-arm32', '--image', 'gcr.io/$PROJECT_ID/cloudbuild-arm32:cloudrun', '--region', 'us-central1']
images:
  - 'gcr.io/$PROJECT_ID/cloudbuild-arm32:arm32'
  - 'gcr.io/$PROJECT_ID/cloudbuild-arm32:cloudrun'
  - 'gcr.io/$PROJECT_ID/cloudbuild-arm32:golang'

