steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t=gcr.io/$PROJECT_ID/cloudbuild-arm32:arm32', '-f=Dockerfile', '.']
    id: build-arm32
    waitFor: ['-']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t=gcr.io/$PROJECT_ID/cloudbuild-arm32:cloudrun', '-f=Dockerfile.cloudrun', '.']
    id: build-cloudrun
    waitFor: ['-']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t=gcr.io/$PROJECT_ID/cloudbuild-arm32:golang', '-f=Dockerfile.golang', '.']
    id: build-golang
    waitFor: ['-']

  - name: 'gcr.io/cloud-builders/docker'
    args: ["push", "gcr.io/$PROJECT_ID/cloudbuild-arm32:cloudrun"]
    id: push-arm32
    waitFor: [build-arm32]

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['alpha', 'serverless', 'deploy', 'cloudbuild-arm32', '--image', 'gcr.io/$PROJECT_ID/cloudbuild-arm32:cloudrun', '--region', 'us-central1']
    id: deploy-cloudrun
    waitFor: [build-cloudrun]

images:
  - 'gcr.io/$PROJECT_ID/cloudbuild-arm32:arm32'
  - 'gcr.io/$PROJECT_ID/cloudbuild-arm32:cloudrun'
  - 'gcr.io/$PROJECT_ID/cloudbuild-arm32:golang'

tags:
  - cloud-run-playground