steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t=gcr.io/$PROJECT_ID/cloudbuild-arm32:arm32', '-f=Dockerfile', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t=gcr.io/$PROJECT_ID/cloudbuild-arm32:cloudrun', '-f=Dockerfile.cloudrun', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t=gcr.io/$PROJECT_ID/cloudbuild-arm32:golang', '-f=Dockerfile.golang', '.']
images:
  - 'gcr.io/$PROJECT_ID/cloudbuild-arm32:arm32'
  - 'gcr.io/$PROJECT_ID/cloudbuild-arm32:cloudrun'
  - 'gcr.io/$PROJECT_ID/cloudbuild-arm32:golang'

