steps:
  - id: build-arm32
    name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t=gcr.io/$PROJECT_ID/cloudbuild-arm32:arm32', '-f=Dockerfile', '.']
    waitFor: ['-']

  - id: build-cloudrun
    name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t=gcr.io/$PROJECT_ID/cloudbuild-arm32:cloudrun', '-f=Dockerfile.cloudrun', '.']
    waitFor: ['-']

  - id: build-golang
    name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t=gcr.io/$PROJECT_ID/cloudbuild-arm32:golang', '-f=Dockerfile.golang', '.']
    waitFor: ['-']

  - id: push-cloudrun
    name: 'gcr.io/cloud-builders/docker'
    args: ["push", "gcr.io/$PROJECT_ID/cloudbuild-arm32:cloudrun"]
    waitFor: [build-cloudrun]

  - id: deploy-cloudrun
    name: 'gcr.io/cloud-builders/gcloud'
    args: ['alpha', 'serverless', 'deploy', 'cloudbuild-arm32', '--image', 'gcr.io/$PROJECT_ID/cloudbuild-arm32:cloudrun', '--region', 'us-central1']
    waitFor: [push-cloudrun]

images:
  - 'gcr.io/$PROJECT_ID/cloudbuild-arm32:arm32'
  - 'gcr.io/$PROJECT_ID/cloudbuild-arm32:cloudrun'
  - 'gcr.io/$PROJECT_ID/cloudbuild-arm32:golang'

tags:
  - cloud-run-playground
  - arm32