FROM resin/raspberry-pi-python:2
RUN apt-get update
RUN sudo apt-get install python-buttonshim python-pip
RUN python -m pip install --upgrade pip # https://stackoverflow.com/questions/49940813/pip-no-module-named-internal
RUN pip install requests
# TODO: Do we need sudo pip install smbus2
ADD src/buttons/rainbow.py /
CMD ["python", "./rainbow.py"]

# On host, sudo raspi-config / 5 Interfacing Options #/ I2C / Enable
# docker build .
# Run with docker run --device /dev/i2c-1 -it <tag>
