FROM resin/raspberry-pi-python:3
RUN apt-get update
RUN sudo apt-get install python3-pip python3-dev python3-numpy
RUN sudo pip3 install inkyphat
ADD src/inky/inky.py /
CMD ["python3", "./inky.py", "Kubernetes"]

# On host, sudo raspi-config / 5 Interfacing Options #/ I2C / Enable
# docker build .
# Run with docker run --device /dev/i2c-1 -it <tag>
