---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pulse-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pulse-demo
  template:
    metadata:
      labels:
        app: pulse-demo
    spec:
      nodeSelector:
        hardware: ledshim
      containers:
      - name: shim
        image: gcr.io/sonorous-crane-219712/cloudbuild-arm32:shim
        resources:
          limits:
            memory: "200Mi"
            cpu: "500m"
        securityContext:
          privileged: true
