---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: buttons-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: buttons-service
  template:
    metadata:
      labels:
        app: buttons-service
    spec:
      nodeSelector:
        hardware: buttons
      containers:
      - name: buttons
        image: gcr.io/sonorous-crane-219712/cloudbuild-arm32:buttons
        imagePullPolicy: Always
        env:
        - name: PYTHONUNBUFFERED
          value: "0"
        resources:
          limits:
            memory: "200Mi"
            cpu: "500m"
        securityContext:
          privileged: true
      imagePullSecrets:
      - name: gcrsecret
