apiVersion: v1
kind: Service
metadata:
  name: inky-service
  labels:
    app: inky-service
spec:
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP
  selector:
    app: inky-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inky-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inky-service
  template:
    metadata:
      labels:
        app: inky-service
    spec:
      nodeSelector:
        hardware: inky
      containers:
      - name: inky
        image: gcr.io/sonorous-crane-219712/cloudbuild-arm32:inky
        imagePullPolicy: Always
        env:
        - name: PYTHONUNBUFFERED
          value: "0"
        resources:
          limits:
            memory: "200Mi"
            cpu: "500m"
        securityContext:
          privileged: true
      imagePullSecrets:
      - name: gcrsecret