---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: led-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: led-service
  template:
    metadata:
      labels:
        app: led-service
    spec:
      nodeSelector:
        hardware: ledshim
      containers:
      - name: led
        image: gcr.io/sonorous-crane-219712/cloudbuild-arm32:led
        # imagePullPolicy: Always
        resources:
          limits:
            memory: "200Mi"
            cpu: "500m"
        securityContext:
          privileged: true
