---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tof-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tof-service
  template:
    metadata:
      labels:
        app: tof-service
    spec:
      nodeSelector:
        hardware: tof
      containers:
      - name: tof
        image: gcr.io/sonorous-crane-219712/cloudbuild-arm32:tof
        # imagePullPolicy: Always
        resources:
          limits:
            memory: "200Mi"
            cpu: "500m"
        securityContext:
          privileged: true
      imagePullSecrets:
      - name: gcrsecret